// sandbox/tml-todo/crosswalk/TodoList.vue
<script setup lang="ts">
/**
 * Vue twin of sandbox/tml-todo (teaching crosswalk).
 * Shape-equivalent to TML project+shell — wire client per trellis/vue docs.
 * Not for Operate/admin chrome.
 */
import { computed } from 'vue';
// import { useEntities, useMutation } from 'trellis/vue/typed';

type Todo = {
  id: string;
  done?: boolean | string;
  title?: string;
};

/** Stand-in: replace with useEntities(client, TodoType) + useMutation(client). */
const todos = computed(() => [] as Todo[]);
const loading = computed(() => false);
async function remove(id: string) {
  // await mutation.remove(id)  ↔  op remove(@todo.id)
  void id;
}
</script>

<template>
  <p v-if="loading">Loading…</p>
  <div v-else data-trellis-ref="todos">
    <div
      v-for="todo in todos"
      :key="todo.id"
      data-trellis-shell="row"
      data-kind="todo"
      :data-entity-id="todo.id"
    >
      <label>
        <span data-trellis-slot="done">{{ todo.done }}</span>
        <span data-trellis-slot="title">{{ todo.title }}</span>
      </label>
      <button type="button" @click="remove(todo.id)">Remove</button>
    </div>
  </div>
</template>

// sandbox/tml-todo/crosswalk/TodoList.tsx
/**
 * React twin of sandbox/tml-todo (teaching crosswalk).
 * Shape-equivalent to TML project+shell — uses trellis/react hooks when wired.
 * Not for Operate/admin chrome.
 */
import { useEntities, useMutation } from 'trellis/react';

type Todo = {
  id: string;
  done?: boolean | string;
  title?: string;
};

export function TodoList() {
  // ↔ project todo.list { query type=Todo; each; live }
  const { data: todos, loading } = useEntities<Todo>({ type: 'Todo' });
  // ↔ op remove(@todo.id)
  const { remove } = useMutation();

  if (loading) return <p>Loading…</p>;

  return (
    <div data-trellis-ref="todos">
      {(todos ?? []).map((todo) => (
        // ↔ shell todo.row
        <div key={todo.id} data-trellis-shell="row" data-kind="todo" data-entity-id={todo.id}>
          <label>
            <span data-trellis-slot="done">{String(todo.done ?? false)}</span>
            <span data-trellis-slot="title">{todo.title}</span>
          </label>
          <button type="button" onClick={() => remove(todo.id)}>
            Remove
          </button>
        </div>
      ))}
    </div>
  );
}
